
import common.net.Network;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * Launcher.java
 *
 * Created on 02.05.2010, 16:17:41
 */

/**
 * J.A.F.S. Game Launcher
 * @author Julian Sanio
 */
public class Launcher extends javax.swing.JFrame implements ActionListener  {

    /** Creates new form Launcher */
    public Launcher() {
        initComponents();
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J.A.F.S. Game Launcher");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/common/resource/Logo.png"))); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jButton1.setText("Client");
        jPanel1.add(jButton1);

        jButton2.setText("Server");
        jPanel1.add(jButton2);

        jButton3.setText("Masterserver");
        jPanel1.add(jButton3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/common/resource/weapon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Checking Java version >= 6
        if ( Double.parseDouble(System.getProperty("java.version").substring(0, 3)) >= 1.6 ) {
            if( args.length >= 2 ) {
                if( args[0].equals("master") ) {
                    // launch masterserver
                    masterserver.Main.main(new String[0]);
                }
                else if( args[0].equals("server") ) {
                    // launch server -> args[1] = ip+port
                    server.Main.main(args);
                }
                else if( args[0].equals("client") ) {
                    // launch client -> args[1] = ip+port
                    System.setProperty("Dsun.java2d.opengl", "True");
                    client.Main.main(args);
                }
            }
            else {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        Launcher uiLauncher = new Launcher();
                        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                        uiLauncher.setLocation(screenSize.width/2-uiLauncher.getWidth()/2, screenSize.height/2-uiLauncher.getHeight()/2);
                        uiLauncher.setVisible(true);
                    }
                });
            }
        }
        else {
            // fehlermeldung java 6 re
            javax.swing.JOptionPane.showMessageDialog(null, "The Game requires Java 6, please install the latest JRE!", "Error", javax.swing.JOptionPane.OK_CANCEL_OPTION);
        }
    }

    /**
     * Invoked when an action occurs.
     * @param e ActionEvent
     */
    public void actionPerformed(ActionEvent e) {
        // launch client
        if(e.getSource().equals(jButton1)) {
            dispose();
            client.Main.main(new String[0]);
        }
        // launch server
        else if(e.getSource().equals(jButton2)) {
//            dispose();
            new server.ui.DlgGUI(this, false).setVisible(true);
        }
        // launch masterserver
        else {
            Network.MASTERHOST = "localhost";
            Network.MASTERPORT = Network.getFreePort(30000, 40000);
            jButton3.setEnabled(false);
            masterserver.Main.main(new String[0]);
            jButton3.setText("gestartet");
        }
    }
}
