/*
 * TestMenu.java
 *
 * Created on 12.03.2010, 11:17:45
 */

package client.ui;

import java.awt.event.ActionEvent;

/**
 *
 * @author Administrator
 */
public class TestMenu extends UiWindow {

    /** Creates new form TestMenu */
    public TestMenu() {
        super(200, 200);
        initComponents();
        jButton1.addActionListener(this);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(null);

        jButton1.setText("Blaaaaaaa");
        add(jButton1);
        jButton1.setBounds(0, 0, 73, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 20, 166, 96);
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(ActionEvent e) {
        System.out.println("Bla");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
